name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: latest

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: |
          # Workaround for https://github.com/nrwl/nx/issues/21823
          mkdir node_modules -p && touch node_modules/.modules.yaml
          pnpm install --frozen-lockfile --ignore-scripts
          pnpm exec playwright install-deps
          pnpm exec playwright install
      - uses: nrwl/nx-set-shas@v4
      - run: pnpm test
